# Calcolo Numerico

https://numpy.org/

In [9]:
import numpy

In [10]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
numpy.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [12]:
numpy.arange(0, 10.1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [17]:
valori = numpy.linspace(-4, 4, 50)
valori

array([-4.        , -3.83673469, -3.67346939, -3.51020408, -3.34693878,
       -3.18367347, -3.02040816, -2.85714286, -2.69387755, -2.53061224,
       -2.36734694, -2.20408163, -2.04081633, -1.87755102, -1.71428571,
       -1.55102041, -1.3877551 , -1.2244898 , -1.06122449, -0.89795918,
       -0.73469388, -0.57142857, -0.40816327, -0.24489796, -0.08163265,
        0.08163265,  0.24489796,  0.40816327,  0.57142857,  0.73469388,
        0.89795918,  1.06122449,  1.2244898 ,  1.3877551 ,  1.55102041,
        1.71428571,  1.87755102,  2.04081633,  2.20408163,  2.36734694,
        2.53061224,  2.69387755,  2.85714286,  3.02040816,  3.18367347,
        3.34693878,  3.51020408,  3.67346939,  3.83673469,  4.        ])

In [15]:
len(valori)

50

In [21]:
numpy.linspace(-4, 4, 51)

array([-4.  , -3.84, -3.68, -3.52, -3.36, -3.2 , -3.04, -2.88, -2.72,
       -2.56, -2.4 , -2.24, -2.08, -1.92, -1.76, -1.6 , -1.44, -1.28,
       -1.12, -0.96, -0.8 , -0.64, -0.48, -0.32, -0.16,  0.  ,  0.16,
        0.32,  0.48,  0.64,  0.8 ,  0.96,  1.12,  1.28,  1.44,  1.6 ,
        1.76,  1.92,  2.08,  2.24,  2.4 ,  2.56,  2.72,  2.88,  3.04,
        3.2 ,  3.36,  3.52,  3.68,  3.84,  4.  ])

In [19]:
import numpy as np

In [20]:
t = np.linspace(0,100, 200)

velocita = 3

In [21]:
spazio = velocita * t

In [22]:
spazio

array([  0.        ,   1.50753769,   3.01507538,   4.52261307,
         6.03015075,   7.53768844,   9.04522613,  10.55276382,
        12.06030151,  13.5678392 ,  15.07537688,  16.58291457,
        18.09045226,  19.59798995,  21.10552764,  22.61306533,
        24.12060302,  25.6281407 ,  27.13567839,  28.64321608,
        30.15075377,  31.65829146,  33.16582915,  34.67336683,
        36.18090452,  37.68844221,  39.1959799 ,  40.70351759,
        42.21105528,  43.71859296,  45.22613065,  46.73366834,
        48.24120603,  49.74874372,  51.25628141,  52.7638191 ,
        54.27135678,  55.77889447,  57.28643216,  58.79396985,
        60.30150754,  61.80904523,  63.31658291,  64.8241206 ,
        66.33165829,  67.83919598,  69.34673367,  70.85427136,
        72.36180905,  73.86934673,  75.37688442,  76.88442211,
        78.3919598 ,  79.89949749,  81.40703518,  82.91457286,
        84.42211055,  85.92964824,  87.43718593,  88.94472362,
        90.45226131,  91.95979899,  93.46733668,  94.97

## Oprazione comuni

In [27]:
np.max(spazio)

300.0

In [28]:
np.min(spazio)

0.0

In [30]:
np.average(spazio)

149.99999999999997

In [23]:
import math

In [24]:
math.sin(0)

0.0

In [25]:
math.cos(0)

1.0

In [27]:
np.sin(t)

array([ 0.        ,  0.481629  ,  0.84417544,  0.99799984,  0.90506919,
        0.58836056,  0.12618003, -0.36719847, -0.7697873 , -0.98204653,
       -0.95149517, -0.68568702, -0.25034303,  0.24689816,  0.68309389,
        0.95039493,  0.98271122,  0.77205257,  0.37050423, -0.12265112,
       -0.58548103, -0.903551  , -0.99821836, -0.84607664, -0.48474282,
       -0.00355654,  0.4785091 ,  0.84226356,  0.9977687 ,  0.90657594,
        0.59123265,  0.12970734, -0.36388806, -0.76751229, -0.98136942,
       -0.95258337, -0.68827147, -0.25378474,  0.24345017,  0.68049212,
        0.94928268,  0.98336348,  0.77430807,  0.37380531, -0.11912066,
       -0.58259409, -0.90202138, -0.99842425, -0.84796714, -0.4878505 ,
       -0.00711303,  0.47538314,  0.84034102,  0.99752493,  0.90807122,
        0.59409727,  0.13323301, -0.36057305, -0.76522757, -0.98067989,
       -0.95365952, -0.69084722, -0.25722323,  0.2399991 ,  0.67788175,
        0.94815841,  0.9840033 ,  0.77655378,  0.37710166, -0.11

In [ ]:
np.